import Navbar from "./Components/navigation/Navbar";
import Footer from "./Components/navigation/Footer";
import Posts from "./Components/Posts/Posts";
import Feedhome from "./Components/feed";
import AppHeader from "./layout/AppHeader";
import AppSidebar from "./layout/AppSidebar";
import SidebarWidget from "./layout/SidebarWidget";

import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pattes Douces",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <AppHeader />
        <div className="flex flex-col md:flex-row">
          <AppSidebar />
          <div className="flex-1">
            {children}
          </div>
          <SidebarWidget />
        </div>
        <Footer />
      </body>
    </html>
  );
}
