import Navbar from "./Components/navigation/Navbar";
import Footer from "./Components/navigation/Footer";
import Home from "./Components/Home/Home";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Home />
        <Footer />
        {children}
      </body>
    </html>
  );
}